export const mockFrames = [
  {
    id: "FRAME-001",
    name: "Classic Rectangle",
    brand: "FRAMEIQ Essentials",
    frameShape: "Rectangle",
    widthCategory: "Medium",
    bridgeType: "Standard",
    frameThickness: "Medium",
    color: "Black",
    style: "Professional",
    price: 129.00,
    currency: "USD",
    image_url: "/frames/frame-001.jpg",
    overlay_url: "/frames/overlay-rectangle.png",
    compatibility_tags: ["Oval", "Round", "Professional", "Medium"]
  },
  {
    id: "FRAME-002",
    name: "Modern Round",
    brand: "FRAMEIQ Essentials",
    frameShape: "Round",
    widthCategory: "Medium",
    bridgeType: "Standard",
    frameThickness: "Thin",
    color: "Tortoise",
    style: "Creative",
    price: 149.00,
    currency: "USD",
    image_url: "/frames/frame-002.jpg",
    overlay_url: "/frames/overlay-round.png",
    compatibility_tags: ["Square", "Rectangle", "Creative", "Medium"]
  },
  {
    id: "FRAME-003",
    name: "Classic Aviator",
    brand: "Aero",
    frameShape: "Aviator",
    widthCategory: "Wide",
    bridgeType: "High bridge",
    frameThickness: "Thin",
    color: "Gold",
    style: "Classic",
    price: 189.00,
    currency: "USD",
    image_url: "/frames/frame-003.jpg",
    overlay_url: "/frames/overlay-aviator.png",
    compatibility_tags: ["Heart", "Oval", "Classic", "Wide"]
  },
  {
    id: "FRAME-004",
    name: "Minimal Clear",
    brand: "ClearSight",
    frameShape: "Geometric",
    widthCategory: "Medium",
    bridgeType: "Standard",
    frameThickness: "Bold",
    color: "Clear",
    style: "Minimalist",
    price: 159.00,
    currency: "USD",
    image_url: "/frames/frame-004.jpg",
    overlay_url: "/frames/overlay-geometric.png",
    compatibility_tags: ["Oval", "Diamond", "Minimalist", "Medium"]
  },
  {
    id: "FRAME-005",
    name: "Bold Wayfarer",
    brand: "Retro",
    frameShape: "Wayfarer",
    widthCategory: "Wide",
    bridgeType: "Standard",
    frameThickness: "Bold",
    color: "Black",
    style: "Bold",
    price: 119.00,
    currency: "USD",
    image_url: "/frames/frame-005.jpg",
    overlay_url: "/frames/overlay-wayfarer.png",
    compatibility_tags: ["Round", "Oval", "Bold", "Wide"]
  },
  {
    id: "FRAME-006",
    name: "Elegant Cat-Eye",
    brand: "Chic",
    frameShape: "Cat-Eye",
    widthCategory: "Narrow",
    bridgeType: "Standard",
    frameThickness: "Medium",
    color: "Dark Blue",
    style: "Fashion-forward",
    price: 169.00,
    currency: "USD",
    image_url: "/frames/frame-006.jpg",
    overlay_url: "/frames/overlay-cateye.png",
    compatibility_tags: ["Square", "Heart", "Fashion", "Narrow"]
  }
];

export type Frame = typeof mockFrames[0];
